

document.write(' <div class="services " style="">');
document.write('       <div class="container">');
document.write('         <div class="row">');
document.write('           <div class="col-md-12">');
document.write('             <div class="section-heading text-center ">');
document.write('               <h2>Contacta con nosotros</h2>');
document.write('             </div>');
document.write('           </div>');
document.write('           <div class="col-md-4">');
document.write('             <div class="team-member founder shadow">');
document.write('               <div class="thumb-container p-2">');
document.write('                 <img class="rounded" src="assets/images/mauricio-gonzalez-vitrificados-boyaca.jpg" alt="">');
document.write('               </div>');
document.write('               <div class="down-content">');
document.write('                 <h4 class="">Mauricio González</h4>');
document.write('                 <span class="">Ventas</span>');
document.write('                 <a class="btn btn-warning" href="https://tel:573107777611"><i class="fa fa-phone text-success"></i> Contactar</a>');
document.write('               </div>');
document.write('             </div>');
document.write('           </div>');
document.write('           <div class="col-md-4">');
document.write('             <div class="team-member founder shadow">');
document.write('               <div class="thumb-container p-2">');
document.write('                 <img class="rounded" src="assets/images/edwin-gonzalez-vitrificados-boyaca.jpg" alt="">');
document.write('               </div>');
document.write('               <div class="down-content">');
document.write('                 <h4 class="">Edwin González</h4>');
document.write('                 <span class="">Gerente</span>');
document.write('                 <a class="btn btn-warning" href="https://tel:573002345416"><i class="fa fa-phone text-success"></i> Contactar</a>');
document.write('               </div>');
document.write('             </div>');
document.write('           </div>');
document.write('           <div class="col-md-4">');
document.write('             <div class="team-member founder shadow">');
document.write('               <div class="thumb-container p-2">');
document.write('                 <img class="rounded" src="assets/images/alejandra-munebar-vitrificados-boyaca.jpg" alt="">');
document.write('               </div>');
document.write('               <div class="down-content">');
document.write('                 <h4 class="">Alejandra Munebar</h4>');
document.write('                 <span class="">PQRs</span>');
document.write('                 <a class="btn btn-warning" href=""><i class="fa fa-phone text-success"></i> Contactar</a>');
document.write('               </div>');
document.write('             </div>');
document.write('           </div>');
document.write('         </div>');
document.write('       </div>');
document.write('     </div>');

